### ISSUE TITLE
Parameter 'read_from' don't used in code

### ISSUE THREAD

**Issue by zomberg** [symfony/AsseticBundle#355]
I suggest will add using this parameter or generate correct web URI for CSS and JS files in method  https://github.com/symfony/AsseticBundle/blob/master/Twig/AsseticExtension.php#L63

Also 'read_from' must be prefix for URI part, not a directory.
```yml
assetic:
    read_from: "/assets"
    write_to: "%kernel.root_dir%/../web/assets"
```

Files must be written and read from web/assets directory.
