### ISSUE TITLE
Asset version for combined assets

### ISSUE THREAD

**Issue by Kezino** [symfony/AsseticBundle#367]
Greetings!

I cannot figure our whether it is possible to assign versions (packages) to combined asset files. This is what I want to do:

```twig
{% javascripts output="js/combined/main.js" package="core"
    '@AppBundle/Resources/public/js/*'
    '@AcmeBarBundle/Resources/public/js/form.js'
    '@AcmeBarBundle/Resources/public/js/calendar.js' %}
    <script src="{{ asset_url }}"></script>
{% endjavascripts %}
```

```yml
...
framework:
    templating:
        packages:
            core:
                version:              0.03
                version_format:       v%%2$s/%%1$s
                base_urls:
                    http: http://mydomain.com
                    ssl: https://mydomain.com
```

The desired output for the combined assets file would be 
```html
...
<script src="http://mydomain.com/v0.03/js/combined/main.js"></script>
...
```

Thank you in advance!
