### ISSUE TITLE
Error when searching for UglifyJS and UglifyCSS binaries

### ISSUE THREAD

**Issue by Pierstoval** [symfony/AsseticBundle#369]
It's been a long time since I had this bug in prod (debian7) and on my MacOS, and could never find how to solve it, because it works on my Windows environment (and actually the OS does not seem to matter, or I don't know how it works...).
 
When you install UglifyJS and UglifyCSS **locally** (I mean in `%kernel.root_dir%/../node_modules`) and want to use them, dumping the assets with assetic will not work for these two libraries.
 
Actually, after some debugging, I found that the `UglifyJsFilter` class (as well as `UglifyCssFilter`) are not constructed with the correct binary value.

We'll take the example for `UglifyJS` only, because it's almost the same for `UglifyCSS`.
 
The default value for the `$uglifyjsBin` is `/usr/bin/uglifyjs`.
When I set this on my assetic config:

```yml
assetic:
        uglifyjs:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
```

The `node_paths` is never used, and I have big error:

```
  [Assetic\Exception\FilterException]
  An error occurred while running:
  '/usr/local/bin/node' '/usr/bin/uglifyjs' '--no-mangle' '-o' '/private/var/folders/5m/q3lzl3_523db19syzdt5dp3wpkwfgy/T/outputtnnslf' '/private/var/folders/5m/q3lzl3_523db19syzdt5dp3wpkwfgy/T/inputZAkrYE'
  Error Output:
  module.js:338
      throw err;
            ^
  Error: Cannot find module '/usr/bin/uglifyjs'
      at Function.Module._resolveFilename (module.js:336:15)
      at Function.Module._load (module.js:278:25)
      at Function.Module.runMain (module.js:501:10)
      at startup (node.js:129:16)
      at node.js:814:3
```

As said, uglifyjs is **not installed globally**, and the uglifyjs binary is located in `{project_dir}/node_modules/uglify-js/bin/uglifyjs`.

To solve this issue for both UglifyJS and UglifyCSS, I had to add this to my configuration:

```yml
# app/config/config.yml
parameters:
    assetic.filter.uglifyjs.bin: %node_modules_path%/uglify-js/bin/uglifyjs
    assetic.filter.uglifycss.bin: %node_modules_path%/uglifycss/uglifycss
```

I could not find any documentation about this, so it could be cool to first fix this when instantiating these filter classes, but I don't know how it's done in the bundle (seems too complex for me sorry for that :disappointed: ).

**Note:** Also, the UglifyJS filter does not work with UglifyJS 2.4+ and I had to force `2.3.*` version in my `package.json` file.

**Comment by Ninir** [comment]
Hey @Pierstoval,

this is the configuration I have at the moment, which is working pretty well:

```yaml

assetic:
    ...
    node: %node_bin_path%
    node_paths: %node_lib_paths%
    filters:
        uglifyjs2:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
```

Where `node_bin_path` is the absolute path to node, and `node_lib_paths` the absolute path to globally installed libs.
All of my binaries are installed in the project using npm, hence the paths you're seeing ;-)
(Using `"uglifycss": "0.0.15"` and `"uglify-js": "2.4.21"` as packages)

Hope it helps!
